name: email_otp
description: A fast & simple email authentication OTP sender and verification flutter package.
version: 3.0.1
homepage: https://rohitchouhan.com
repository: https://github.com/rohit-chouhan/email_otp

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

screenshots:
  - description: 'Email OTP Logo'
    path: logo.png

topics:
  - email
  - otp
  - smtp
  - authentication
